sudo: required
services:
  - docker

before_install:
  - docker build -t aebenw/travis-image -f Dockerfile.dev .

script:
  - docker run aebenw/travis-image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-demo"
  env: "DockerDemo-env"
  bucket_name: "elasticbeanstalk-us-east-1-281758552871"
  bucket_path: "docker-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
